#ifndef SERVO_CONFIG_H
#define SERVO_CONFIG_H

#define SERVO_PORT DIOA
#define SERVO_PORT_RCC DIOA_RCC

#define SERVO_STEERING PWM_CHANNEL_1
#define SERVO_RIGHT_MIRROR PWM_CHANNEL_2
#define SERVO_LEFT_MIRROR PWM_CHANNEL_3
#define SERVO_CHAIR PWM_CHANNEL_4

#endif